x-default-environment: &default-environment
  TZ: "UTC"
  NODE_ENV: development
  DB_HOST: db
  DB_USERNAME: &default-db-username sa
  DB_DATABASE: &default-db-name traditional_knowledge_development
  DB_PASSWORD: &default-db-password DevPwd99!
  DB_PORT: &default-db-port 1433
  DB_TRUST_SERVER_CERTIFICATE: "true"
  DB_HEALTH_CHECK_INTERVAL_SECONDS: 5
  DB_HEALTH_CHECK_TIMEOUT_SECONDS: 10
  DB_HEALTH_CHECK_RETRIES: 3
  DB_HEALTH_CHECK_START_PERIOD_SECONDS: 5
  FRONTEND_URL: "http://localhost:8080"
  VITE_APPLICATION_NAME: "Traditional Knowledge"
  VITE_API_BASE_URL: "http://localhost:3000"
  VITE_AUTH0_CLIENT_ID: "fsWyrDohhHtojdOpOFnAYtFMxwAMHUEF"
  VITE_AUTH0_AUDIENCE: "testing"
  VITE_AUTH0_DOMAIN: "https://dev-0tc6bn14.eu.auth0.com"
  RELEASE_TAG: "${RELEASE_TAG:-development}"
  GIT_COMMIT_HASH: "${GIT_COMMIT_HASH:-not-set}"
  MAIL_HOST: "mail"
  MAIL_PORT: 1025
  MAIL_FROM: "traditional-knowledge.development@yukon.ca"
  MAIL_SERVICE: "MailDev"
  REDIS_CONNECTION_URL: "redis://@cache:6379"
  PDF_SIGNER_JAR: "/var/lib/open-pdf-sign.jar"
  TIMESTAMP_SERVER: "http://timestamp.digicert.com"
  SSL_FULL_CHAIN_PATH: "/etc/ssl/certs/fullchain.pem"
  SSL_CERT_KEY_PATH: "/etc/ssl/private/icefog.pem"
  BLOB_CONTAINER: "the-vault"

services:
  api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
      args:
        USER_ID: ${HOST_USER_ID:-1000}
        GROUP_ID: ${HOST_GROUP_ID:-1000}
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
      TS_NODE_HISTORY: /usr/src/api/.ts_node_repl_history
    tty: true # allows attaching debugger, equivalent of docker exec -t
    init: true
    # stdin_open: true # equivalent of docker exec -i
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
    volumes:
      - ./api:/usr/src/api
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - db
      - mail
      - cache

  web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
      args:
        USER_ID: ${HOST_USER_ID:-1000}
        GROUP_ID: ${HOST_GROUP_ID:-1000}
    environment:
      <<: *default-environment
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    ports:
      - "8080:8080"
    volumes:
      - ./web:/usr/src/web
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      api:
        condition: service_started

  test_api:
    build:
      context: ./api
      dockerfile: development.Dockerfile
      args:
        USER_ID: ${HOST_USER_ID:-1000}
        GROUP_ID: ${HOST_GROUP_ID:-1000}
    command: /bin/true
    env_file:
      - ./api/.env.development
    environment:
      <<: *default-environment
      NODE_ENV: test
      DB_DATABASE: traditional_knowledge_test
      DEFAULT_LOG_LEVEL: "info"
      DB_HEALTH_CHECK_START_PERIOD_SECONDS: 0
      TS_NODE_HISTORY: /usr/src/api/.ts_node_repl_history
    tty: true
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    volumes:
      - ./api:/usr/src/api
      - ./api/.env.development:/usr/src/api/.env.test
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - db
      - mail
      - cache

  test_web:
    build:
      context: ./web
      dockerfile: development.Dockerfile
      args:
        USER_ID: ${HOST_USER_ID:-1000}
        GROUP_ID: ${HOST_GROUP_ID:-1000}
    command: /bin/true
    environment:
      <<: *default-environment
      NODE_ENV: test
    tty: true
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    volumes:
      - ./web:/usr/src/web
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml

  cache:
    image: bitnamilegacy/redis:8.0.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    user: root
    environment:
      <<: *default-environment
      DB_HOST: "localhost"
      MSSQL_SA_PASSWORD: *default-db-password
      TZ: "America/Whitehorse"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql/data

  mail:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP

  # For easily generating large PlantUML diagrams
  # Not relevant to production environment.
  # Accessible at http://localhost:9999
  # Use with: dev up --profile design (and dev down --profile design)
  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - "9999:8080"
    environment:
      PLANTUML_LIMIT_SIZE: 8192
    profiles:
      - design

  archiver:
    build:
      context: ./archiver
      dockerfile: development.Dockerfile
      args:
        USER_ID: ${HOST_USER_ID:-1000}
        GROUP_ID: ${HOST_GROUP_ID:-1000}
    env_file:
      - ./archiver/.env.development
    environment:
      <<: *default-environment
    tty: true # allows attaching debugger, equivalent of docker exec -t
    # stdin_open: true # equivalent of docker exec -i
    user: "${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}"
    ports:
      - "5000:5000"
    volumes:
      - ./archiver/certs/icefog.pem:/etc/ssl/private/icefog.pem:ro
      - ./archiver/certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./archiver:/usr/src/archiver
      - ./.gitignore:/usr/src/.gitignore
      - ./.prettierrc.yaml:/usr/src/.prettierrc.yaml
    depends_on:
      - db
      - cache

volumes:
  db_data:
